sudo: false
language: node_js
node_js:
  - "9.10"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - NODE_ENV=development npm run deploy
  - NODE_ENV=production npm run deploy
